
I2C_DRIVER_REQUIRED = yes
MCU = STM32F411
BOARD = BLACKPILL_STM32_F411

BOOTMAGIC_ENABLE = yes
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

# Wichtig:
I2C_DRIVER = I2CD1
I2C_DRIVER = yes
MCP23017_DRIVER = yes

# CUSTOM_MATRIX = lite
# SRC += matrix.c
